### ISSUE TITLE
Always getting total = 0 when making a UtilsApi query

### ISSUE THREAD

**Issue by mitchdowney** [manticoresoftware/manticoresearch-javascript#11]
I'm using v2.0.3. I have a query like this:  
  
```  
const result = await utilsApi.sql(`  
    SELECT *  
    FROM idx_media_ref  
    WHERE match('*${searchTitle}*')  
    ORDER BY weight() DESC, ${orderByColumnName} ${orderByDirection}  
    LIMIT ${skip},${take}  
    OPTION ranker=expr('sum(lcs*user_weight)');  
```
  
```  
  
And I want to know how many rows matched this query, but the `total` value in the response is always equal to 0.   
  
Example response:  
  
```  
result {  
  columns: [  
    { id: [Object] },  
    { podverse_id: [Object] },  
    { title: [Object] },  
    { created_date: [Object] }  
  ],  
  data: [  
    {  
      id: 103,  
      podverse_id: 'fR1ISSE2_w',  
      title: 'Another soundbite title',  
      created_date: 1604987327  
    }  
  ],  
  total: 0,  
  error: '',  
  warning: ''  
}  
```  
  
Is there something I need to add to the query to get the # of matching rows as the total? Or is this a limitation of manticoresearch-javascript?

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
No, the query is ok. This problem did exist in Manticore 4.2.0, irrespective of client.  It's fixed now in 4.2.1 (dev version) so you can use it to avoid the issue.
