### ISSUE TITLE
Incorrent behavior of JSON.parse for id

### ISSUE THREAD

**Issue by egorkazantsev** [manticoresoftware/manticoresearch-javascript#13]
Execute of `select id from table where id=8216118575463666095` returns `{id: 8216118575463666000}`  
  
This problem describes in https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin  
  
Bellow screenshot of execution manticoresearch-javascript client:  
  
![image](https://gitlab.com/manticoresearch/openapi/uploads/d01cc677ddbd764f3e4e61f6de574fac/1650874020_165045930-5ebbffac-8476-44e4-b7a5-c80b96c37f7a.png)

**Comment by sanikolaev** [comment]
BTW it also fails in JQ version 1.6 (latest at the moment):

```
➜  ~ echo '{"id": 8216118575463666095}'|jq .
{
  "id": 8216118575463666000
}
```

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
As this issue relates to the basic constraint of Javascript's `number` type  (`Number.MAX_SAFE_INTEGER =  
9007199254740991`), we now handle it by converting such data to `string` when parsing JSON response.
