### ISSUE TITLE
Transaction in SQL over HTTP?

### ISSUE THREAD

**Issue by UtfCube** [manticoresoftware/manticoresearch-javascript#14]
The Manticoresearch documentation says, that HTTP connection supports Keep-Alive header ([src](https://manual.manticoresearch.com/Connecting_to_the_server/HTTP#SQL-over-HTTP)).  
  
Is it possible to use transactions in SQL over HTTP in this case?  
If this is possible, then you need to somehow pass the `superagent` instance to the `ApiClient.callApi` method from the outside, since now every time `ApiClient.callApi` method is called new instances of `superagent` is created and Keep-Alive headers in the request makes no sense.  
  
Lines number 392 in `ApiClient.js`:  
    `var request = superagent(httpMethod, url);`

**Comment by sanikolaev** [comment]
> Is it possible to use transactions in SQL over HTTP in this case?

Yes, here's an example in pure HTTP https://www.youtube.com/watch?v=LYVajGLq_pQ

> If this is possible, then you need to somehow pass the superbase instance to the ApiClient.callApi method from the outside

Can you think of how exactly this can be done and make a pull request?

**Comment by UtfCube** [comment]
@sanikolaev Yes, I think i can give it a shot. Great project btw, I really love it)

**Comment by UtfCube** [comment]
@sanikolaev I found pretty simple solution. Based on [this topic](https://stackoverflow.com/questions/20743546/keep-alive-connection-with-superagent/26324362#26324362), I create instance of `agentkeepalive` and pass it to `ApiClient` constructor via `requestAgent` option, and this fixed the problem. 
I think, maybe this worth mentioned in Readmy of this package?

**Comment by UtfCube** [comment]
@sanikolaev Standart node.js `http.Agent` is worked better. With `agentkeepalive` I get a lot of ECONNRESET and ETIMEDOUT errors on response.

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
We've added the `requestAgent` option information to the client's README
