### ISSUE TITLE
How to use it in React?

### ISSUE THREAD

**Issue by nw-engineer** [manticoresoftware/manticoresearch-javascript#16]
Hello.

I would like to use this wonderful tool in React.

How can I make it available in React?

**Comment by Nick-S-2018** [comment]
Hello,
Unfortunately, you cannot use this client with React, as it is.
You would need to generate a separate ts client with the [OpenAPI generator](https://openapi-generator.tech/). Here is its [Github repo](https://github.com/OpenAPITools/openapi-generator)
We welcome cooperation, so if you're interested in the subject, you can generate and test the client, and send us a PR.
