### ISSUE TITLE
How to set the manticoresearch server?

### ISSUE THREAD

**Issue by Dreamystify** [manticoresoftware/manticoresearch-javascript#9]
How do you define the baseUrl for the SearchApi?

**Comment by adriannuta** [comment]
```
var Manticoresearch = require('manticoresearch');
    var client= new Manticoresearch.ApiClient()
    client.basePath="http://127.0.0.1:9999";
    searchApi = new Manticoresearch.SearchApi(client);
```
I'll do an update of the docs soon.

**Comment by adriannuta** [comment]
Added in [Readme.md](https://github.com/manticoresoftware/manticoresearch-javascript/blob/master/README.md) at 63444738633e8d73e07cfa5bdeedd8b7c252ec2d

**Comment by dimuska139** [comment]
@adriannuta code example of current README version ("A simple search case") is incorrect because of `client` variable is undefined.

**Comment by tomatolog** [comment]
could you create PR with correct example?

**Comment by dimuska139** [comment]
@tomatolog https://github.com/manticoresoftware/manticoresearch-javascript/pull/10
